Fb auth (#41)
* save token in localstorage

* fb login

* git hook shenanigans

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -48,8 +48,16 @@ fi
 # If there are whitespace errors, print the offending file names and fail.
 git diff-index --check --cached $against --
 
+# exit on failure
+set -e
+
 # assert that tests pass
 npm run test
+
+if [[ "$?" != 0 ]]; then
+    echo -e "\t\e[31mTESTS FAILED\e[0m"
+    exit 1
+fi
 
 STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")
 
